sass:
  sass_dir: _sass
  style: compressed

# Site contents configuration

permalink: /posts/:categories/:title
contact_email: contact@icrs.io
person_in_charge:
#   eurobot:
#     name: Harry
#     email: harry@icrs.io
#   piwars:
#     name: Harry
#     email: harry@icrs.io
#
events_api_url: http://35.177.234.162:8102/
